### ISSUE TITLE
[JOSS] The second notebook example doesn't work well

### ISSUE THREAD

**Issue by seisman** [trichter/rf#21]
https://nbviewer.jupyter.org/github/trichter/notebooks/blob/master/receiver_function_profile_chile.ipynb

Issues:

1. Need to create a "data" directory before running the script
2. I got following errors, possibly an issue of matplotlib or obspy?
```
Traceback (most recent call last):
  File "/Users/seisman/.anaconda/envs/rfenv/lib/python3.7/site-packages/matplotlib/colors.py", line 109, in _sanitize_extrema
    ret = ex.item()
AttributeError: 'str' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 26, in <module>
    inventory.plot(label=False)
  File "/Users/seisman/.anaconda/envs/rfenv/lib/python3.7/site-packages/obspy/core/inventory/inventory.py", line 749, in plot
    title=None, show=False, fig=fig, **kwargs)
  File "/Users/seisman/.anaconda/envs/rfenv/lib/python3.7/site-packages/obspy/imaging/maps.py", line 768, in plot_map
    return plot_cartopy(*args, **kwargs)
  File "/Users/seisman/.anaconda/envs/rfenv/lib/python3.7/site-packages/obspy/imaging/maps.py", line 553, in plot_cartopy
    scal_map = ScalarMappable(norm=Normalize(min_color, max_color),
  File "/Users/seisman/.anaconda/envs/rfenv/lib/python3.7/site-packages/matplotlib/colors.py", line 909, in __init__
    self.vmin = _sanitize_extrema(vmin)
  File "/Users/seisman/.anaconda/envs/rfenv/lib/python3.7/site-packages/matplotlib/colors.py", line 111, in _sanitize_extrema
    ret = float(ex)
ValueError: could not convert string to float: '#b15928'
```

https://github.com/openjournals/joss-reviews/issues/1808

**Comment by trichter** [comment]
I see, the data directory could be created automatically, if it is not present.

I think the second issue is due to a combination of old obspy and new matplotlib versions. See obspy/obspy#2097 (and others). Can you confirm, that you are not using tha latest ObsPy version `1.1.1`?

**Comment by seisman** [comment]
You're right, my ObsPy version is `1.1.0`, but I followed the install instruction exactly.

**Comment by trichter** [comment]
I cannot reproduce your issue on Linux.

But I noticed, that the latest release on conda-forge pinned the numpy version to `<1.16` (conda-forge/obspy-feedstock#26). Your conda solver probably installed a newer numpy version and therefore obspy `1.1.0`. I think the issue could be solved by using the install line

```
conda create -n rfenv obspy tqdm shapely cartopy geographiclib h5py gfortran_osx-64
```

without the dependencies which are itself dependencies of obspy.

If you could confirm this, I 'd be happy to update the documentation.

**Comment by seisman** [comment]
It works, now I have obspy 1.1.1

**Comment by seisman** [comment]
Now it works well for me.
